version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "kanban-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-bmbcu2he4bve"
s3_prefix = "kanban-api"
region = "sa-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
