Transform: AWS::Serverless-2016-10-31

Description: API for Kanban

Globals:
  Function:
    Timeout: 10
    Environment:
      Variables:
        LISTS_TABLE: !Ref Lists
        CARDS_TABLE: !Ref Cards

Resources:
  KanbanApi:
    Type: AWS::Serverless::HttpApi

  Lists:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: lists
      PrimaryKey:
        Name: uuid
        Type: String
  Cards:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: cards
      PrimaryKey:
        Name: uuid
        Type: String

  ListsIndex:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      PackageType: Zip
      Handler: lists/index.Lists::Index.handler
      Runtime: ruby2.7
      MemorySize: 128
      Timeout: 10
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref Lists
      Events:
        Invoke:
          Type: HttpApi
          Properties:
            Method: GET
            Path: /lists
            ApiId: !Ref KanbanApi

Outputs:
  LambdaProjectHttpApiUrl:
    Description: Kanban API URL
    Value: !Sub https://${KanbanApi}.execute-api.${AWS::Region}.amazonaws.com/
